# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb-pre}
  s.version = "1.1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["The Merb Team"]
  s.date = %q{2009-11-18}
  s.description = %q{install this before you gem install merb --prerelease}
  s.email = %q{team@merbivore.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION"
  ]
  s.homepage = %q{http://merbivore.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Metagem that contains all the prerelease files for merb}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<extlib>, [">= 0.9.13"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.6.2"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 1.1.9"])
      s.add_runtime_dependency(%q<ParseTree>, [">= 2.1.1"])
      s.add_runtime_dependency(%q<mailfactory>, [">= 1.2.3"])
      s.add_runtime_dependency(%q<templater>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<haml>, [">= 2.0.3"])
      s.add_runtime_dependency(%q<dm-core>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-migrations>, ["~> 0.10"])
      s.add_runtime_dependency(%q<do_sqlite3>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-timestamps>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-types>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-validations>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-sweatshop>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-serializer>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-constraints>, ["~> 0.10"])
      s.add_runtime_dependency(%q<merb>, [">= 1.1.0.pre"])
    else
      s.add_dependency(%q<extlib>, [">= 0.9.13"])
      s.add_dependency(%q<erubis>, [">= 2.6.2"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
      s.add_dependency(%q<ruby2ruby>, [">= 1.1.9"])
      s.add_dependency(%q<ParseTree>, [">= 2.1.1"])
      s.add_dependency(%q<mailfactory>, [">= 1.2.3"])
      s.add_dependency(%q<templater>, [">= 1.0.0"])
      s.add_dependency(%q<haml>, [">= 2.0.3"])
      s.add_dependency(%q<dm-core>, ["~> 0.10"])
      s.add_dependency(%q<dm-migrations>, ["~> 0.10"])
      s.add_dependency(%q<do_sqlite3>, ["~> 0.10"])
      s.add_dependency(%q<dm-timestamps>, ["~> 0.10"])
      s.add_dependency(%q<dm-types>, ["~> 0.10"])
      s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_dependency(%q<dm-validations>, ["~> 0.10"])
      s.add_dependency(%q<dm-sweatshop>, ["~> 0.10"])
      s.add_dependency(%q<dm-serializer>, ["~> 0.10"])
      s.add_dependency(%q<dm-constraints>, ["~> 0.10"])
      s.add_dependency(%q<merb>, [">= 1.1.0.pre"])
    end
  else
    s.add_dependency(%q<extlib>, [">= 0.9.13"])
    s.add_dependency(%q<erubis>, [">= 2.6.2"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
    s.add_dependency(%q<ruby2ruby>, [">= 1.1.9"])
    s.add_dependency(%q<ParseTree>, [">= 2.1.1"])
    s.add_dependency(%q<mailfactory>, [">= 1.2.3"])
    s.add_dependency(%q<templater>, [">= 1.0.0"])
    s.add_dependency(%q<haml>, [">= 2.0.3"])
    s.add_dependency(%q<dm-core>, ["~> 0.10"])
    s.add_dependency(%q<dm-migrations>, ["~> 0.10"])
    s.add_dependency(%q<do_sqlite3>, ["~> 0.10"])
    s.add_dependency(%q<dm-timestamps>, ["~> 0.10"])
    s.add_dependency(%q<dm-types>, ["~> 0.10"])
    s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
    s.add_dependency(%q<dm-validations>, ["~> 0.10"])
    s.add_dependency(%q<dm-sweatshop>, ["~> 0.10"])
    s.add_dependency(%q<dm-serializer>, ["~> 0.10"])
    s.add_dependency(%q<dm-constraints>, ["~> 0.10"])
    s.add_dependency(%q<merb>, [">= 1.1.0.pre"])
  end
end

